[package]
name = "make-sysroot"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
inquire = "0.7.5"
pathdiff = "0.2.3"
walkdir = "2.5.0"
